### ISSUE TITLE
Hvor mange bruker console?

### ISSUE THREAD

**Issue by jhrv** [nais/console-frontend#3]
Hvor mange bruker console?
Hvilke side-kategorier besøkes mest?

Instrumentere med Amplitude, kanskje?

**Comment by jhrv** [comment]
Hadde du gjort noe her allerede @thokra-nav ?

**Comment by thokra-nav** [comment]
Ikke noe mer enn amplitude dashboardet

**Comment by thokra-nav** [comment]
Er amplitude godt nok til å kunne lukke denne @jhrv ?

**Comment by jhrv** [comment]
Jepp 👌
