### ISSUE TITLE
GAR Image size/list etc

### ISSUE THREAD

**Issue by thokra-nav** [nais/console-frontend#37]
On occasion, users request some way to see/manage/track GAR images. Should we add some more data into Console about the images stored in GAR?

One use case from today:
- Track image size over time

**Comment by jhrv** [comment]
Can you link an example request? Also, what is the motivation/reason for this? Image-size over time seems like something that has a wierd fit in the platform IMO, even more so if we are going to start automatically cleaning up images and make GAR more transparent.

**Comment by thokra-nav** [comment]
We're now auto cleaning GAR, closing this as solved
