### ISSUE TITLE
secrets: relax key name restrictions

### ISSUE THREAD

**Issue by dagframstad** [nais/console-frontend#55]
## Beskrivelse / Essensen

Lette på restriksjoner for nøkler tilhørende Secrets slik at vi også tillater `-` og `.`

## Investeringsvilje

<1 uke

## Mulig løsning i grove trekk

Oppdatere valideringskode i console-frontend og api:

- https://github.com/nais/console-frontend/blob/f3f86d7005e198f19dcbf4eee71157a126b924bb/src/routes/team/%5Bteam%5D/(teamPages)/%5Benv%5D/secret/%5Bsecret%5D/AddKeyValue.svelte#L31-L53
- https://github.com/nais/api/blob/65dd40901795fe86ac55bc4568e93394264c1020/internal/k8s/secrets.go#L393-L416

For api kan man evt. bare bruke [`validation.IsEnvVarName()`](https://github.com/kubernetes/kubernetes/blob/v1.30.0/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L428-L436) direkte.

---

## Original comment below:

We have code that does stuff with files at startup depending on the file extension.
It would be nice to be able to use a dot (.) in a secrets key. This would be very handy when mounting the secret as a file (using fromFiles in the nais manifest).
I understand that it's impossible if the secret is used as an environment entry (envFrom), but you could fail application startup if a secret with a dot in the key is used as an environment variable (or be nice and replace the dot with an underscore at startup).

And while I'm at it, why not allow dash, -, as well?

**Comment by tronghn** [comment]
Please correct me if I've misunderstood, but the short version is that you would like to be able to use the `.` and `-` characters when defining Secret keys? 🙂

The original intention was to be compliant with the POSIX shell standards for environment variable names, though this evidently complicates matters when a Secret is mounted as files.

We're likely not going to introduce implicit behaviours that modify or replace keys as that will only lead to further confusion, but we can consider relaxing the current restrictions similarily to https://github.com/kubernetes/kubernetes/pull/48986

**Comment by dagframstad** [comment]
Yes, thats exactly what I want.
