### ISSUE TITLE
Ressursbruk for Naisjobs i Console

### ISSUE THREAD

**Issue by Kyrremann** [nais/console-frontend#79]
## Beskrivelse / Essensen

I #67 ble utilization (aka ressursbruk) i Console implementert. Den lot brukerne se hvor mye CPU og minne appen deres bruker, og hva ubrukte ressurser koster. De som bruker Naisjob har ikke den samme muligheten til å se sin ressursbruk i Console.

## Investeringsvilje

1 uke

## Ikke-mål

- Vise kostnader for en jobb

## Mulig løsning i grove trekk

Implementerer utilization for Naisjob så likt som Apps som mulig.

## Eventuell annen relevant informasjon

![Image](https://github.com/nais/console-frontend/assets/1830501/8d55fea4-0503-4e7a-ad4e-400edc239949)

# Shapers
- @Kyrremann

**Comment by thokra-nav** [comment]
Litt utfordring med denne er å faktisk få verdifull data for jobber. Hvis de kjører over en lengre tid, så er det nok data, men for korte jobber så kan det fort være at dataen enten ikke eksisterer eller er helt på jorde. 

Bør kanskje ha med en bit som handler om å estimere hvor god dataen er, og hvorvidt vi skal vise data for de som ikke har god data.

**Comment by jhrv** [comment]
Det gir ikke mening å ha utilization på samme måte for jobs som for apper slik det er skissert opp, da de ikke kjører kontinuerlig slik som apper. 
Så om vi har data nok til å si noe om hvor godt jobben utnytter ressursene, så må det visualiseres annerledes og tenkes helt nytt (og det bør inngå i denne shapen). Hvorvidt vi har data bør være en del av shapingen, da det er en klar forutsetning. 

En annen ting er at verdien av å vise utilization for en job er ganske mye mindre, da det ikke utgjør særlig mye besparelse i ressurser da de ikke blir allokert når jobben ikke kjører.

**Comment by Kyrremann** [comment]
Hvis vi mener at det ikke er nok å hente (eller nok å spare) for å få jobber til å be om mer "riktig" ressursbruk, så tipper jeg hele denne shapen kan skrotes.

**Comment by thokra-nav** [comment]
Tenker vi burde gitt jobber litt ekstra kjærlighet, men akkurat ressursbruk tilsvarende applications. Men det som sikkert kunne vært kult var å ha info om kjøretid, gjerne ressursbruk under kjøretiden, antall instanser osv

**Comment by jhrv** [comment]
Jeg tror vi har lyst til å se litt større på/zoome litt lenger ut, når det kommer til Jobs. Enig at det fortjener å få litt mer kjærlighet, og mer hensiktsmessige views og funksjonalitet tilpasset jobs. Ikke bare copy/paste av hva enn som har skjedd med Applications.

**Comment by jhrv** [comment]
Lukker denne inntil videre, ref diskusjon
